### PR TITLE
Fix SLES15 values for virtual_alias_db_type

### PR DESCRIPTION
**Pull request by anders-larsson**

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
Looks better to me ;)
Sorry and thank you !!

**Comment by anders-larsson** [comment]
Any ideas on CI / Spec Puppet 6 and why it might be failing?

**Comment by anders-larsson** [comment]
Any ideas @Phil-Friderici ? Guess there is some incompatibility issues between gems specified in Gemfile on older versions of ruby? Why are we not using PDK for the spec tests btw?

**Comment by Phil-Friderici** [comment]
> Any ideas @Phil-Friderici ? Guess there is some incompatibility issues between gems specified in Gemfile on older versions of ruby?

I guess it's on Puppetlabs to fix the PDK and related Gems. Whatever I tried, didn't work out.

> Why are we not using PDK for the spec tests btw?

Any idea how to do so ? I only found this Github action to run the unit/acceptance tests.

**Comment by anders-larsson** [comment]
> Any idea how to do so ? I only found this Github action to run the unit/acceptance tests.

After looking around the options seems to be limited. There are a few for spec tests but nothing for acceptance tests. The reason why I mentioned it is because it seems to work fine with if you run it through pdk with --puppet-version instead of using bundle directly.

Should we make our own attempt in creating a Github action for PDK?

**Comment by Phil-Friderici** [comment]
> Should we make our own attempt in creating a Github action for PDK?

I think the Github action we use did work well quite some time. I guess that Puppetlabs fix their dependencies and the action will continue to work well again then. We just need to wait.

I think we could skip Puppet 6 unit test by removing support for it from metadata.json. As Puppet 6 isn't important for us, I think we should take that route instead. Once PDK get updated to fully support Puppet 8 we would have again two major versions to get tested.

**Comment by anders-larsson** [comment]
Sounds sane. Will you create a separate change request to remove it or should I?

**Comment by Phil-Friderici** [comment]
Should be easier for you to modify the PR ;)

**Comment by anders-larsson** [comment]
Is it OK to include it in this PR?

**Comment by Phil-Friderici** [comment]
Make it it's own commit and I think it should be good enough.

**Comment by anders-larsson** [comment]
OK. Just need to figure out how it works then. Looks like it's looping every some list it gets from somewhere. Not sure where  the variable comes from though.

**Comment by Phil-Friderici** [comment]
I would start with putting this into metadata.json:

```
  "requirements": [
    {
      "name": "puppet",
      "version_requirement": ">= 7.0.0 < 9.0.0"
    }
  ],
```

**Comment by anders-larsson** [comment]
I suspect that might be the case. Seems a bit sad though because the module ought to still work on Puppet 6.

**Comment by Phil-Friderici** [comment]
I am sure it will work fluently with Puppet 6, we only skip verifying it.

**Comment by anders-larsson** [comment]
Of course it will. It will just announce that the module "officially" supports it.. since metadata is just metadata after all.

I'll fix it.

**Comment by anders-larsson** [comment]
Are we OK to merge this?

**Pull request merged**
