### PR TITLE
Use EPP templates

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Comment by anders-larsson** [comment]
We shouldn't fully utilise the epp functionality and use parameters for the template? Will of course be a lot of extra parameters thoiugh.

**Comment by Phil-Friderici** [comment]
Added parameters to the EPP and manifest. Had issues with `Array($main_mynetworks, true)` after adding the parameters to the template. Looked like the array wasn't really empty, after changing to `any2array` it worked well again :)

Just a though:
Maybe we should drop support for strings when actually an array should be used ?
That would be: main_mynetworks & main_inet_interfaces.
When releasing a new major version we can destroy backward compatibility ;)

**Comment by anders-larsson** [comment]
> Maybe we should drop support for strings when actually an array should be used ?
> That would be: main_mynetworks & main_inet_interfaces.

I agree with this. Might as well.

**Comment by Phil-Friderici** [comment]
Changed the mentioned parameters to be array only. Will use a new major version once release.
Next week I will check which Postfix parameters to add natively to the module.
After that we can finally add more OS families ;)

**Comment by anders-larsson** [comment]
Great. I'll go through the OSs currently not added and add configuration for them.

Forgot, we still you still wanted to add new parameters for the most common options. Is this still kthe case?

**Comment by Phil-Friderici** [comment]
Yes, I am adding new params in at the moment and will create a new PR for these. So better wait a little bit before adding new OSs ;)

Let's discuss which new params should get added over there...

**Comment by Phil-Friderici** [comment]
The new PR is here: https://github.com/kodguru/puppet-module-postfix/pull/66

**Pull request merged**
