### PR TITLE
SLES/SLED 15.5 support

### PR DESCRIPTION
**Pull request by anders-larsson**
Based on #73 which should be merged first.

### CODE REVIEW

**Comment by anders-larsson** [comment]
We're still missing tests for actual minor releases of SLES/SLED. This was removed from the previous pull request. Is it something we want to re-implement somehow? Should be it's own pull request though.

**Comment by Phil-Friderici** [comment]
> We're still missing tests for actual minor releases of SLES/SLED.

We have specific tests for 10/12 and 15. Which ones are missing ?

**Comment by anders-larsson** [comment]
I mean to detect issues such as the one fixed in #73 where the db_type was set incorrectly.  Does this pull request look OK to you btw?

**Comment by anders-larsson** [comment]
Oh. Found a bug.
`smtpd_enforce_tls: no` gets converted to `smtpd_enforce_tls = false`. Need to stringify 'no' in YAML file. Will fix.

**Comment by anders-larsson** [comment]
Works correctly now.

**Comment by Phil-Friderici** [comment]
Your PR looks good to me.

Regarding the tests for Susie minor versions: Could you create a ticket for it ? Than I can asign to it in the next sprint.

**Comment by anders-larsson** [comment]
Rebased it on master after merging the other pull request. Will merge once tests has gone through.

I'll create a issue and assign it to you.

**Comment by anders-larsson** [comment]
Will you create a new release after this pull request has been released or should I?

BR

**Comment by Phil-Friderici** [comment]
If you can wait, I can create a new release after the tests have been added/fixed. Otherwise feel free to create a new release.

**Comment by anders-larsson** [comment]
OK, as long as the spec tests update are finished within a reasonable time we can wait for them before releasing.

**Pull request merged**
