### PR TITLE
Add Acceptance Testing

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Adding acceptance testing that runs automatically with GitHub Action. It's based on Litmus.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
Please check https://github.com/kodguru/puppet-module-postfix/actions/runs/3602013506/jobs/6068468501

**Comment by anders-larsson** [comment]
Looks good. What are our thoughts about the errors we have in some containers?

**Comment by Phil-Friderici** [comment]
> What are our thoughts about the errors we have in some containers?

I am not sure what you mean ? Acceptance testing issues or Postfix related issues ?

**Comment by anders-larsson** [comment]
I'm referring to all comments in https://github.com/kodguru/puppet-module-postfix/pull/55/files#diff-8b5cd9eecd02f5a1a06b2885b017c1a9af68064b76ff17bf8a84aa5edd5adcc7R5

**Comment by Phil-Friderici** [comment]
Some OS behaves strange and I'm working on them to get them fixed.

**Comment by Phil-Friderici** [comment]
Fixed CentOS 8/9

**Comment by Phil-Friderici** [comment]
Fixes CentOS 8 & 9, added OracleLinux & ScientificLinux.
My testing with Debian wasn't successfull so far, Puppet client is missing, needs troubleshooting.

**Comment by Phil-Friderici** [comment]
@anders-larsson litmus:debian images currently are not able to retrieve the Puppet agent packages. Seems like the download script wants to use the debian release names (squeeze, bullseye) but isn't able to find it. Will troubleshoot a little bit more and create an issue in https://github.com/puppetlabs/litmusimage then.

Should we merge this ?

**Review by anders-larsson — APPROVED** [review]
Looks good to me!

**Pull request merged**
