### PR TITLE
More Susies

### PR DESCRIPTION
**Pull request by Phil-Friderici**
Based on the work of @anders-larsson I have fixed the 'global' spec tests.

### CODE REVIEW

**Comment by anders-larsson** [comment]
Hm, but this prevents us from testing minor releases (each which might be different configuration) on SLES again? The reason it was implemented was so we could test each minor release. Now we're just testing the major release or am I missing something?

**Comment by Phil-Friderici** [comment]
> am I missing something?

My idea here is to have the 'global' spec tests testing the versions (and minors) as facterdb will serve them.
To cover the versions (and minors) that have deviations or are missing (SLES 10) will get their own specific tests. Like I did with SLES10 and Ubuntu 22.04.

So for SLES 15 we would add a specific test file to make sure the deviations are covered.

**Comment by anders-larsson** [comment]
OK. Will you add these tests for SLES 15 specifically? Should i close #67?

**Comment by Phil-Friderici** [comment]
Yes, I'll add new specific tests for the minor versions.
Yes, please close #67, let's continue work here.

Could you please add source files of main.cf for Suse 12.x too ? Guess this will ease the work very much :)

**Comment by Phil-Friderici** [comment]
> OK. Will you add these tests for SLES 15 specifically?

they just materialized ;)

**Comment by Phil-Friderici** [comment]
@anders-larsson Could you please add source files of main.cf for Suse 12.x too ? I don't have access to all the different minor versions of Suse 12.

**Comment by anders-larsson** [comment]
> @anders-larsson Could you please add source files of main.cf for Suse 12.x too ? I don't have access to all the different minor versions of Suse 12.

Let me see what I can get. Not sure I'll be provide all minor releases.

**Comment by anders-larsson** [comment]
> @anders-larsson Could you please add source files of main.cf for Suse 12.x too ? I don't have access to all the different minor versions of Suse 12.

Let me see what I can get. Not sure I'll be provide all minor releases.

**Comment by anders-larsson** [comment]
Rebased a few commits and updated their contents and added a separate commit with other SLES 12.x sources. Not sure why every commit shows my avatar now. Looking at them however shows you as the author.

**Comment by anders-larsson** [comment]
SLES 12.0 data is missing. Maybe we should just copy SLES 12.1 to 12.0 since at least 12.1 and 12.2 are the same.

**Comment by anders-larsson** [comment]
There are merge conflicts in some files now. You probably want to get rid of the merge commit as well.

**Comment by anders-larsson** [comment]
OK. I fixed the merge commit stuff. Please don't add merge commits! :p

**Comment by Phil-Friderici** [comment]
> OK. I fixed the merge commit stuff.

Thanks !

> Please don't add merge commits! :p

Think we are ready now!
Should I rebase all these commits into one before merging ?

**Comment by anders-larsson** [comment]
Uhm. It's up to you. Something like "Update SLES configuration"?

**Comment by Phil-Friderici** [comment]
From my perspective it's ready to merge now.

**Comment by anders-larsson** [comment]
Looks OK to me. You don't want a "Co-authored-by" added to recognise your contributions to this?

**Pull request merged**
